[connections.snowflake]
account = "VLSOZBY-PMB51598"
user = "AKAGAN2"
password = "dWOm!Qskyy0V1sU@"
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = true
